import {test,expect} from '@playwright/test';
import {CASES} from '../../src/content.js';
import {openRecord,seedRole,acceptSpoilers,observeSpeech,expectSpeech,wav} from './dubbing-helpers.mjs';
import {recordingControl} from './dubbing-helpers.mjs';
test.beforeEach(async({page})=>{await page.route('**/api/dubbing/access',r=>r.fulfill({json:{unlocked:true}}));});

test('casting shows real counts, uniform spoiler consent, and the complete safe quick role',async({page})=>{
 await page.goto('/?test-profile=choice');await page.locator('#start').click();await expect(page.locator('#choose-quick')).toContainText('5 משפטים');await page.locator('#choose-voice').click();
 await expect(page.locator('[data-voice]')).toHaveCount(6);for(const card of await page.locator('.voice-card').all()){await expect(card).toContainText('13 משפטים');await expect(card).toContainText('13 חדשים');await expect(card).toContainText('הערכה');}
 await page.locator('[data-voice="cat"]').click();await expect(page.locator('#full-record')).toBeDisabled();await expect(page.locator('.record-line')).toHaveCount(0);await expect(page.locator('#dialog')).toContainText('האזהרה זהה לכל הדמויות');
 await page.locator('#quick-instead').click();await expect(page.locator('.eyebrow').last()).toContainText('מתוך 5');await expect(page.locator('#play-personal')).toBeDisabled();await expect(page.locator('#play-now')).toBeEnabled();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/complete-role-mobile.png'});
});
test('a real synthetic capture autosaves as a draft, resumes after reload, and cannot cast a partial role',async({page})=>{
 await openRecord(page,'goat','draft-resume');await page.locator('#record-take').click();await expect(page.locator('#stop-take')).toBeEnabled();await page.waitForTimeout(800);await page.locator('#stop-take').click();await expect(page.locator('#record-status')).toContainText('הטיוטה נשמרה בנפרד');await expect(page.locator('#take-count')).toContainText('0 מתוך 13');await expect(page.locator('#play-personal')).toBeDisabled();
 await (await recordingControl(page,'[data-line="4"]')).click();await page.locator('#exit-draft').click();await page.reload();await page.locator('#start').click();await page.locator('#choose-voice').click();await expect(page.locator('.voice-card').first()).toContainText('1 הקלטות תואמות');await page.locator('[data-voice="goat"]').click();await acceptSpoilers(page);await expect(page.locator('.eyebrow').last()).toContainText('משפט 5');
 await (await recordingControl(page,'[data-line="0"]')).click();await expect(page.locator('#listen-take')).toBeEnabled();await expect(page.locator('#accept-take')).toBeEnabled();await page.locator('#listen-take').click();await expect(page.locator('#accept-take')).toBeEnabled();await page.locator('#accept-take').click();await expect(page.locator('#take-count')).toContainText('1 מתוך 13');
 await (await recordingControl(page,'#play-now')).click();await page.locator('#skip-intro').click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('neighborhood-test-draft-resume')).caseCasting.characterId)).toBe(null);
});
test('SYNTHETIC full personal role survives investigation, accusation, reconstruction and fresh next-case casting',async({page})=>{
 test.setTimeout(120000);await observeSpeech(page);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?test-profile=full-case');await seedRole(page,{profile:'full-case',characterId:'cat'});
 await page.reload();await page.locator('#start').click();await page.locator('#choose-voice').click();await page.locator('[data-voice="cat"]').click();await page.locator('#use-complete').click();await page.locator('#skip-intro').click();await expectSpeech(page,'cat.arrival');
 await page.locator('.accessible-map summary').click();await page.locator('[data-resident="cat"]').click();await expectSpeech(page,'cat.greet');await page.locator('[data-question="secret"]').click();await expectSpeech(page,'cat.secret');
 for(const event of ['complaint','boast','question','encounter']){await page.locator('.optional-talk summary').click();await page.locator(`[data-flavor="${event}"]`).click();await expectSpeech(page,`cat.${event==='encounter'?'arrival':event}`);}
 await page.locator('#leave-person').click();await page.locator('#bell').click();await expectSpeech(page,'cat.bell');await page.locator('[data-resident="cat"]').click();await page.locator('#leave-person').click();await page.locator('#sprinkler').click();await expectSpeech(page,'cat.water');
 await page.locator('#guide-action').click();await expect(page.locator('#guide-action')).toHaveText('לבדוק מה קרה',{timeout:22000});await page.locator('#guide-action').click();
 await page.locator('[data-resident="cat"]').click();await expectSpeech(page,'cat.fire.comment');await page.locator('[data-question="alibi"]').click();await expectSpeech(page,'cat.fire.alibi');await page.locator('[data-question="detail"]').click();await expect(page.locator('.speech')).not.toContainText('הצתתי');await page.locator('#leave-person').click();
 for(const location of ['home','delivery','center','shed']){await page.locator(`[data-location="${location}"]`).click();await page.locator('#back-world').click();}await page.locator('[data-resident="goat"]').click();await page.locator('[data-question="alibi"]').click();await page.locator('#leave-person').click();
 await page.locator('#accuse').click();await page.locator('[data-suspect="cat"]').click();for(const id of ['fire-scene','fire-luggage','fire-entry','fire-tools'])await page.locator(`input[value="${id}"]`).check();await page.locator('#review-accusation').click();await page.locator('#submit-accusation').click();await expectSpeech(page,'cat.wrong');
 await page.locator('#edit-accusation').click();for(const input of await page.locator('.clue-card input').all())await input.uncheck();for(const id of CASES[0].proofGroups.map(g=>g[0]))await page.locator(`input[value="${id}"]`).check();await page.locator('#review-accusation').click();await page.locator('#submit-accusation').click();await expectSpeech(page,'cat.fire.detail','personal',25000);await expect(page.locator('#next-case')).toBeVisible({timeout:33000});
 const events=await page.evaluate(()=>window.speechEvents.filter(e=>e.characterId==='cat'));expect(events.length).toBeGreaterThan(10);expect(events.every(e=>e.source==='personal')).toBe(true);expect(await page.evaluate(()=>window.mouthEvents.some(e=>e.resident==='cat'&&e.mouth>0))).toBe(true);
 await page.locator('#next-case').click();await expect(page.locator('#creator-start')).toBeVisible();await page.locator('#choose-voice').click();const card=page.locator('.voice-card').filter({has:page.locator('[data-voice="cat"]')});await expect(card).toContainText('10 הקלטות תואמות');await expect(card).toContainText('3 חדשים');await (await recordingControl(page,'#play-now')).click();await expect(page.locator('#begin-case')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('neighborhood-test-full-case')).caseCasting)).toMatchObject({caseId:'courtyard',characterId:null,mode:'creator'});expect(errors).toEqual([]);
});
test('personal media failure shows subtitles, offers repair after the dialogue, and never requests creator replacement',async({page})=>{
 await observeSpeech(page);await page.addInitScript(()=>{const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){return window.breakPersonal&&this.src.startsWith('blob:')?Promise.reject(new DOMException('Synthetic playback failure','NotSupportedError')):play.call(this);};});
 const creatorRequests=[];await page.route('**/assets/voices/available.json',r=>r.fulfill({json:{'cat.greet':{file:'/creator-cat.wav',scriptVersion:2}}}));await page.route('**/creator-cat.wav',r=>{creatorRequests.push(r.request().url());return r.fulfill({body:wav(),contentType:'audio/wav'});});
 await page.goto('/?test-profile=repair');await seedRole(page,{profile:'repair',characterId:'cat'});await page.reload();await page.locator('#start').click();await page.locator('#choose-voice').click();await page.locator('[data-voice="cat"]').click();await page.locator('#use-complete').click();await page.locator('#skip-intro').click();await page.evaluate(()=>window.breakPersonal=true);
 await page.locator('.accessible-map summary').click();await page.locator('[data-resident="cat"]').click();await expectSpeech(page,'cat.greet','personal-subtitles');await expect(page.locator('.speech')).toContainText('מרגלית');expect(creatorRequests).toEqual([]);await expect(page.locator('#repair-voice')).toBeHidden();
 await page.locator('#leave-person').click();await expect(page.locator('#repair-voice')).toBeVisible();await page.locator('#repair-voice').click();await acceptSpoilers(page);await expect(page.locator('#play-personal')).toBeDisabled();await expect(page.locator('#play-now')).toContainText('חזרה');await (await recordingControl(page,'#play-now')).click();await page.locator('#guide-action').click();await expect(page.locator('#guide-action')).toHaveText('לבדוק מה קרה',{timeout:22000});
});
for(const [caseId,index,characterId] of [['fire',0,'badger'],['courtyard',1,'badger'],['balcony',2,'hedgehog']])test(`SYNTHETIC complete quick role ${caseId}: early voice and every supporting branch`,async({page})=>{
 test.setTimeout(60000);await observeSpeech(page);const profile='quick-'+caseId;await page.goto('/?test-profile='+profile);await seedRole(page,{profile,caseId,characterId});await page.reload();await page.locator('#choose-start').click();await page.locator(`[data-case="${index}"]`).click();await page.locator('#choose-quick').click();await page.locator('#use-complete').click();if(index===0)await page.locator('#skip-intro').click();else await page.locator('#begin-case').click();await expectSpeech(page,`${characterId}.intro`);
 await page.locator('.accessible-map summary').click();await page.locator(`[data-location="${index===2?'home':'garden'}"]`).click();await page.locator('#meet-support').click();
 for(const button of await page.locator('[data-support-event]').all()){const event=await button.getAttribute('data-support-event');await page.locator(`[data-support-event="${event}"]`).click();}
 await page.locator('#support-back').click();await page.locator('#guide-action').click();await expect(page.locator('#guide-action')).toHaveText('לבדוק מה קרה',{timeout:22000});await page.locator('#guide-action').click();
 await page.locator(`[data-location="${index===2?'home':'garden'}"]`).click();if(index===1){await expect(page.locator('#meet-support')).toHaveCount(0);await page.locator('#back-world').click();}else{await page.locator('#meet-support').click();for(const event of index===0?['care','copies','receipt']:['pause','space'])await page.locator(`[data-support-event="${event}"]`).click();await page.locator('#support-back').click();}
 const result=await page.evaluate(async({caseId,characterId})=>{const {requiredLines}=await import('/src/dialogue-manifest.js');return {required:requiredLines(caseId,characterId).map(l=>l.id),heard:[...new Set(window.speechEvents.filter(e=>e.characterId===characterId&&e.source==='personal').map(e=>e.lineId))],other:window.speechEvents.filter(e=>e.characterId===characterId&&e.source!=='personal')};},{caseId,characterId});expect(result.heard.sort()).toEqual(result.required.sort());expect(result.other).toEqual([]);
});
