import {test,expect} from '@playwright/test';
import {openRecord,acceptSpoilers} from './dubbing-helpers.mjs';
test('record, review, approve, reload, replace and delete a draft line; partial role starts only with creator',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await openRecord(page);
 await expect(page.locator('#accept-take')).toBeDisabled();await page.locator('#record-take').click();await expect(page.locator('#stop-take')).toBeEnabled();await page.waitForTimeout(1100);await page.locator('#stop-take').click();await expect(page.locator('#listen-take')).toBeEnabled();await expect(page.locator('#accept-take')).toBeDisabled();await page.locator('#listen-take').click();await expect(page.locator('#accept-take')).toBeEnabled();await page.locator('#accept-take').click();await expect(page.locator('#take-count')).toContainText('1 מתוך 13');await expect(page.locator('#play-personal')).toBeDisabled();
 await page.locator('#play-now').click();await page.locator('#skip-intro').click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('neighborhood-test-browser')).caseCasting.mode)).toBe('creator');
 await openRecord(page);await expect(page.locator('#listen-take')).toBeEnabled();await page.locator('#record-take').click();await expect(page.locator('#stop-take')).toBeEnabled();await page.waitForTimeout(700);await page.locator('#stop-take').click();await page.locator('#listen-take').click();await expect(page.locator('#accept-take')).toBeEnabled();await page.locator('#accept-take').click();await expect(page.locator('#take-count')).toContainText('1 מתוך 13');await page.locator('[data-line="1"]').click();await page.locator('[data-line="0"]').click();await page.locator('#delete-take').click();await expect(page.locator('#take-count')).toContainText('0 מתוך 13');await expect(page.locator('#listen-take')).toBeDisabled();expect(errors).toEqual([]);
});
test('microphone denial leaves immediate creator play available',async({page})=>{
 await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await openRecord(page,'cat');await page.locator('#record-take').click();await expect(page.locator('#record-status')).toContainText('נדחתה');await page.locator('#play-now').click();await expect(page.locator('#begin-case')).toBeVisible();
});
test('unsupported MediaRecorder leaves subtitles and immediate play available',async({page})=>{
 await page.addInitScript(()=>{window.MediaRecorder=undefined;});await openRecord(page,'turtle');await page.locator('#record-take').click();await expect(page.locator('#record-status')).toContainText('אינו תומך');await page.locator('#play-now').click();await expect(page.locator('#begin-case')).toBeVisible();
});
test('enhanced draft stores processing settings; device-ended discards only the active take',async({page})=>{
 await page.addInitScript(()=>{const get=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async opts=>{const s=await get(opts);window.testStream=s;return s;};});await openRecord(page,'boar');await page.locator('#enhance-voice').check();await page.locator('#record-take').click();await expect(page.locator('#stop-take')).toBeEnabled();await page.waitForTimeout(600);await page.locator('#stop-take').click();await page.locator('#listen-take').click();await expect(page.locator('#accept-take')).toBeEnabled();await page.locator('#accept-take').click();await expect(page.locator('#take-count')).toContainText('1 מתוך 13');
 expect(await page.evaluate(async()=>{const {VoiceStore}=await import('/src/voice-store.js'),{LINE}=await import('/src/content.js');const s=new VoiceStore({name:'neighborhood-voices-test-browser'});await s.ready;const settings=s.get(LINE['boar.greet']).processing;s.db.close();return settings.enhance&&settings.highpassHz===85&&settings.compressorRatio===2;})).toBe(true);
 await page.locator('[data-line="1"]').click();await page.locator('#record-take').click();await expect(page.locator('#stop-take')).toBeEnabled();await page.evaluate(()=>window.testStream.getAudioTracks()[0].dispatchEvent(new Event('ended')));await expect(page.locator('#record-status')).toContainText('נותק');await expect(page.locator('#accept-take')).toBeDisabled();await expect(page.locator('#record-take')).toBeEnabled();
});
test('leaving during recording stops tracks and leaves completed drafts intact',async({page})=>{
 await page.addInitScript(()=>{const get=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async opts=>{const s=await get(opts);window.testStream=s;return s;};});await openRecord(page,'pigeon');await page.locator('#record-take').click();await expect(page.locator('#stop-take')).toBeEnabled();await page.locator('#change-voice').click();await expect.poll(()=>page.evaluate(()=>window.testStream.getTracks().every(t=>t.readyState==='ended'))).toBe(true);await page.locator('[data-voice="pigeon"]').click();await acceptSpoilers(page);await expect(page.locator('#take-count')).toContainText('0 מתוך 13');
});
test('RTL mobile full-role grouping, skip and creator start without recording',async({page})=>{
 await page.setViewportSize({width:390,height:844});await openRecord(page,'snake');await expect(page.locator('html')).toHaveAttribute('dir','rtl');await page.locator('#skip-take').click();await expect(page.locator('.eyebrow').last()).toContainText('משפט 2');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/quick-dubbing-mobile.png'});await page.locator('#change-voice').click();await expect(page.locator('[data-voice]')).toHaveCount(6);await page.locator('#play-now').click();await page.locator('#skip-intro').click();await expect(page.locator('#overlay')).toBeHidden();
});
test('creator path starts immediately and tutorial is preserved',async({page})=>{
 await page.goto('/?test-profile=creator');await page.locator('#start').click();await page.locator('#creator-start').click();await page.locator('#begin-case').click();await page.locator('#guide-action').click();await expect(page.locator('#dialog-title')).toHaveText('ירחמיאל');await page.locator('#leave-person').click();await expect(page.locator('#guide-objective')).toContainText('עדשה');
});
