import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function start(page,tutorial=false){await page.goto('/?test-profile=interaction-'+(tutorial?'guided':'free'));await page.locator('#start').click();await page.locator('#creator-start').click();await page.locator(tutorial?'#begin-case':'#skip-intro').click();}
async function point(page,x,y){const b=await page.locator('#world').boundingBox();return {x:b.x+x*b.width/1000,y:b.y+y*b.height/760};}
async function tapWorld(page,x,y,touch=false){await page.locator('#world').scrollIntoViewIfNeeded();const p=await point(page,x,y);if(touch)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);}
async function overlappingSpawns(page,point=[830,355]){let source=await readFile('src/residents.js','utf8');source=source.replace('spawn:[345,365]',`spawn:[${point}]`).replace('spawn:[641,390]',`spawn:[${point}]`);await page.route('**/src/residents.js',r=>r.fulfill({body:source,contentType:'text/javascript'}));}
const stage=(page,value)=>expect(page.locator('#tutorial-coach')).toHaveAttribute('data-step',value);
test('overlap picker selects every resident and the notice, closes outside/Escape, pauses time and has no click-through',async({page})=>{
 await overlappingSpawns(page);await start(page);await page.locator('#pause').click();
 await tapWorld(page,830,334);await expect(page.locator('#target-picker')).toBeVisible();
 for(const id of ['goat','pigeon','cat'])await expect(page.locator(`[data-target="resident:${id}"]`)).toBeVisible();await expect(page.locator('[data-target="location:home"]')).toContainText('לקרוא את ההודעה');
 await page.screenshot({path:'test-results/overlap-picker-desktop.png',fullPage:true});await page.locator('[data-target="resident:pigeon"]').click();await expect(page.locator('#dialog-title')).toHaveText('נבו');await expect(page.locator('#target-picker-layer')).toBeHidden();await page.locator('#leave-person').click();await expect(page.locator('#pause')).toHaveAttribute('aria-label','המשך');
 await tapWorld(page,830,334);await page.locator('[data-target="resident:goat"]').click();await expect(page.locator('#dialog-title')).toHaveText('ירחמיאל');await page.locator('#leave-person').click();
 await tapWorld(page,830,334);await page.locator('[data-target="location:home"]').click();await expect(page.locator('#dialog')).toContainText('התצפית נוספה');await page.locator('#back-world').click();
 await tapWorld(page,830,334);await page.keyboard.press('Escape');await expect(page.locator('#target-picker-layer')).toBeHidden();await expect(page.locator('#overlay')).toBeHidden();
 await tapWorld(page,830,334);await page.mouse.click(8,8);await expect(page.locator('#target-picker-layer')).toBeHidden();await expect(page.locator('#overlay')).toBeHidden();
 await page.locator('#pause').click();await tapWorld(page,830,334);const time=await page.locator('#time').textContent();await page.waitForTimeout(3500);await expect(page.locator('#time')).toHaveText(time);await page.keyboard.press('Escape');
 await page.locator('#lens').click();await tapWorld(page,830,334);await expect(page.locator('#target-picker-layer')).toBeHidden();await expect(page.locator('#overlay')).toBeHidden();
});
test('focused tutorial: correct actions, drag through shade, notebook entry, optional night, first clue and witness',async({page})=>{
 test.setTimeout(60000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await start(page,true);await stage(page,'lens');await expect(page.locator('#tutorial-text')).toContainText('לחצו על העדשה');const time=await page.locator('#time').textContent();
 await page.locator('#bell').click({force:true});await page.waitForTimeout(1200);await stage(page,'lens');await expect(page.locator('#time')).toHaveText(time);
 await page.locator('#lens').click();await stage(page,'place-lens');await tapWorld(page,700,420);await stage(page,'place-lens');await expect(page.locator('#overlay')).toBeHidden();
 const a=await point(page,720,435),b=await point(page,345,315);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:12});await page.mouse.up();await stage(page,'watch');await expect(page.locator('#tutorial-watch-progress')).toBeVisible();
 await page.screenshot({path:'test-results/tutorial-watch-desktop.png'});await stage(page,'notebook-before');await expect(page.locator('#time')).toHaveText(time);await page.locator('#notebook').click();await stage(page,'notebook-entry');await expect(page.locator('#entry-watch-goat')).toBeVisible();
 await page.locator('#entry-watch-goat summary').click();await stage(page,'notebook-return');await expect(page.locator('#entry-watch-goat')).toContainText('לא הוכחה לאשמה');await page.locator('#notebook-close').click();await expect(page.locator('#tutorial-coach')).toBeHidden();await expect(page.locator('#night-invitation-note')).toBeVisible();await expect(page.locator('#phase')).toHaveText('תצפית');
 await page.waitForTimeout(2000);await expect(page.locator('#phase')).toHaveText('תצפית');await page.locator('#next-action').click();await expect(page.locator('#night-invitation-note')).toBeHidden();await expect(page.locator('#guide-action')).toHaveText('לבדוק מה קרה',{timeout:22000});await page.locator('#guide-action').click();await stage(page,'trace');
 await tapWorld(page,830,320);await stage(page,'trace-return');await page.locator('#back-world').click();await stage(page,'witness');
 // Use the highlighted, moving/rendered target rectangle rather than guessed coordinates.
 const hole=await page.locator('#tutorial-hole').boundingBox();await page.mouse.click(hole.x+hole.width/2,hole.y+hole.height*.65);await stage(page,'ask-witness');await page.locator('[data-question="alibi"]').click();await stage(page,'witness-return');await page.locator('#leave-person').click();await expect(page.locator('#tutorial-coach')).toBeHidden();expect(errors).toEqual([]);
});
test('skip and replay recover cleanly, and spotlight follows viewport resizing',async({page})=>{
 await start(page,true);await stage(page,'lens');await page.setViewportSize({width:850,height:650});const button=await page.locator('#lens').boundingBox(),hole=await page.locator('#tutorial-hole').boundingBox();expect(Math.abs(button.x-hole.x-6)).toBeLessThan(3);expect(Math.abs(button.y-hole.y-6)).toBeLessThan(3);
 await page.locator('#tutorial-skip').click();await expect(page.locator('#tutorial-coach')).toBeHidden();await expect(page.locator('#lens')).toHaveText('הרמת עדשה');await page.locator('#context-help').click();await page.locator('#replay-tutorial').click();await page.locator('#creator-start').click();await page.locator('#begin-case').click();await stage(page,'lens');await page.locator('#lens').click();await stage(page,'place-lens');await page.locator('#tutorial-skip').click();await expect(page.locator('#lens')).toHaveText('הרמת עדשה');await page.locator('#next-action').click();await expect(page.locator('#phase')).toHaveText('הלילה יורד');
});
test.describe('mobile touch',()=>{
 test.use({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 test('touch picker stays in viewport at the edge and lens taps never open conversations',async({page})=>{
  await overlappingSpawns(page,[950,430]);await start(page);await page.locator('#pause').tap();await tapWorld(page,955,397,true);await expect(page.locator('#target-picker')).toBeVisible();const bounds=await page.locator('#target-picker').boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(390);expect(bounds.y+bounds.height).toBeLessThanOrEqual(844);await page.screenshot({path:'test-results/overlap-picker-mobile.png'});await page.locator('[data-target="resident:pigeon"]').tap();await expect(page.locator('#dialog-title')).toHaveText('נבו');await page.locator('#leave-person').tap();await page.locator('#lens').tap();await tapWorld(page,955,397,true);await expect(page.locator('#target-picker-layer')).toBeHidden();await expect(page.locator('#overlay')).toBeHidden();
 });
 test('touch tutorial completes basic actions; highlighted night button remains visible',async({page})=>{
  test.setTimeout(60000);
  await start(page,true);await stage(page,'lens');await page.locator('#lens').tap();await stage(page,'place-lens');await tapWorld(page,345,315,true);await stage(page,'notebook-before');await page.locator('#notebook').tap();await stage(page,'notebook-entry');await page.locator('#entry-watch-goat summary').tap();await stage(page,'notebook-return');await expect(page.locator('#entry-watch-goat p')).toBeInViewport();await page.screenshot({path:'test-results/tutorial-notebook-mobile.png'});await page.locator('#notebook-close').tap();await expect(page.locator('#night-invitation-note')).toBeVisible();await page.screenshot({path:'test-results/tutorial-night-mobile.png'});const button=await page.locator('#next-action').boundingBox();expect(button.y+button.height).toBeLessThanOrEqual(844);await expect(page.locator('#tutorial-coach')).toBeHidden();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('#next-action').tap();await expect(page.locator('#guide-action')).toHaveText('לבדוק מה קרה',{timeout:22000});await page.locator('#guide-action').tap();await stage(page,'trace');await tapWorld(page,830,320,true);await stage(page,'trace-return');await page.locator('#back-world').tap();await stage(page,'witness');const target=await page.locator('#tutorial-hole').boundingBox();await page.touchscreen.tap(target.x+target.width/2,target.y+target.height*.65);await stage(page,'ask-witness');await page.locator('[data-question="alibi"]').tap();await stage(page,'witness-return');await page.locator('#leave-person').tap();await expect(page.locator('#tutorial-coach')).toBeHidden();
 });
});
