import test from 'node:test';
import assert from 'node:assert/strict';
import {CASES,VOICES,RESIDENTS,LOCATIONS,LINE} from '../src/content.js';
import {createState,update,inspect,intervene,evaluate,startReconstruction,reconstructionStep,locationById,beginNight,acknowledgeCrime} from '../src/simulation.js';
import {sceneState,INCIDENT_DURATION} from '../src/incidents.js';
const advance=(s,seconds)=>{for(let i=0;i<Math.ceil(seconds*10);i++)update(s,.1);};
function finish(s){s.tutorial.enabled=false;assert(beginNight(s));advance(s,13);assert.equal(s.flow,'discovery');assert(acknowledgeCrime(s));}
const recover=s=>{for(const x of [...LOCATIONS,...RESIDENTS])inspect(s,x.id);};

test('every clickable location and case notice has Hebrew display text',()=>{
 for(const place of LOCATIONS)for(const key of ['name','description']){assert.equal(typeof place[key],'string',`${place.id}.${key}`);assert.match(place[key],/[א-ת]/);assert.doesNotMatch(place[key],/\b(?:undefined|null|NaN)\b/);}
 for(const c of CASES){assert(LOCATIONS.some(place=>place.id===c.preLocation));assert.equal(typeof c.preFact,'string');assert.match(c.preFact,/[א-ת]/);}
});
test('courtyard reconstruction preserves the witnessed order: meeting, death, then stolen notebook',()=>{const s=createState(1);finish(s);const goat=s.residents.find(r=>r.id==='goat'),original={x:goat.x,y:goat.y};startReconstruction(s);const pigeon=s.residents.find(r=>r.id==='pigeon');for(let i=0;i<40;i++)reconstructionStep(s,.1);assert(sceneState(s).badgerAlive);assert.equal(pigeon.carry,null);assert.equal(goat.y,345);for(let i=0;i<40;i++)reconstructionStep(s,.1);assert(sceneState(s).body);assert.equal(pigeon.carry,'notebook');for(let i=0;i<130;i++)reconstructionStep(s,.1);assert.deepEqual({x:goat.x,y:goat.y},original);});
for(const [i,c] of CASES.entries()){
 test(`${c.id}: recover every clue after missing incident; only one supported suspect`,()=>{const s=createState(i);finish(s);recover(s);assert.equal(s.clues.size,c.clues.length);const proof=c.proofGroups.map(g=>g[0]);assert.equal(proof.length,4);for(const r of RESIDENTS)assert.equal(evaluate(s,r.id,proof).ok,r.id===c.culprit);assert.equal(evaluate(s,c.culprit,proof.slice(0,3)).ok,false);assert.equal(evaluate(s,c.culprit,Array(4).fill(proof[0])).ok,false);assert.equal(evaluate(s,c.culprit,['invented',...proof.slice(1)]).ok,false);});
 test(`${c.id}: no alternative four-clue selection proves a different resident`,()=>{const s=createState(i);finish(s);recover(s);const ids=[...s.clues];let valid=0;for(let a=0;a<ids.length;a++)for(let b=a+1;b<ids.length;b++)for(let d=b+1;d<ids.length;d++)for(let e=d+1;e<ids.length;e++){const proof=[ids[a],ids[b],ids[d],ids[e]];for(const r of RESIDENTS){const answer=evaluate(s,r.id,proof);if(answer.ok){valid++;assert.equal(r.id,c.culprit);assert(c.proofGroups.every(g=>g.some(id=>proof.includes(id))));}}}assert(valid>0);});
 test(`${c.id}: spending both interventions cannot destroy evidence`,()=>{const s=createState(i);for(const type of ['bell','sprinkler']){assert(intervene(s,type));assert(intervene(s,type));assert.equal(intervene(s,type),false);}finish(s);recover(s);assert(evaluate(s,c.culprit,c.proofGroups.map(g=>g[0])).ok);});
 test(`${c.id}: observing indefinitely never starts the incident`,()=>{const s=createState(i);advance(s,200);assert.equal(s.flow,'observe');assert.equal(s.crimeDone,false);finish(s);assert(s.crimeDone);});
 test(`${c.id}: sequence cannot be diverted, duplicated, or inspected mid-event`,()=>{const s=createState(i,{tutorial:false});assert(beginNight(s));assert.equal(beginNight(s),false);advance(s,4);assert.equal(s.crimeDone,false);assert.equal(intervene(s,'bell'),false);assert.deepEqual(inspect(s,c.source),[]);advance(s,4);assert(s.crimeDone);assert.equal(s.flow,'night');advance(s,INCIDENT_DURATION);assert.equal(s.flow,'discovery');assert.deepEqual(inspect(s,c.source),[]);acknowledgeCrime(s);advance(s,70);assert.equal(s.events.filter(e=>e.kind==='crime').length,1);});
 test(`${c.id}: reconstruction shows culprit and authored destination; permanent consequences survive`,()=>{const s=createState(i);finish(s);recover(s);const prior=[...s.clues];const consequence=sceneState(s);startReconstruction(s);for(let j=0;j<80;j++)reconstructionStep(s,.1);assert.equal(s.residents.find(r=>r.id===c.culprit).carry,c.item);let done=false;for(let j=0;j<180;j++)done=reconstructionStep(s,.1);assert(done);const r=s.residents.find(r=>r.id===c.culprit);assert.equal(r.x,locationById(c.destination).door.x);assert.equal(r.y,locationById(c.destination).door.y);s.reconstructing=false;assert.deepEqual(sceneState(s),consequence);assert.deepEqual([...s.clues],prior);s.solved=true;assert.equal(sceneState(s).burned,true);if(i===2)assert(sceneState(s).collapsed);});
 test(`${c.id}: scene consequences affect routine targets`,()=>{const s=createState(i);finish(s);s.lens.active=false;advance(s,60);for(const r of s.residents){assert(r.target);assert.notDeepEqual(r.target,locationById('home').door);assert.notDeepEqual(r.target,locationById('garden').door);}});
}
test('incident states are visibly different before, during, and after each authored event',()=>{
 const fire=createState(0,{tutorial:false});assert(!sceneState(fire).burned);beginNight(fire);advance(fire,4);assert(sceneState(fire).fireActive);advance(fire,4);assert(sceneState(fire).burned);advance(fire,5);assert(!sceneState(fire).fireActive);assert(sceneState(fire).smoke);
 const murder=createState(1);assert(sceneState(murder).burned);assert(sceneState(murder).badgerAlive);finish(murder);assert(sceneState(murder).body);assert(!sceneState(murder).badgerAlive);
 const balcony=createState(2);assert(sceneState(balcony).burned&&sceneState(balcony).memorial);assert.equal(sceneState(balcony).hedgehog,'balcony');finish(balcony);assert(sceneState(balcony).collapsed);assert.equal(sceneState(balcony).hedgehog,'injured');
});
test('replay restores canonical earlier scenes and does not inherit later damage or evidence',()=>{const late=createState(2);finish(late);recover(late);late.notes='private';late.attempts=4;for(const i of [0,1,2]){const s=createState(i);assert.equal(s.clues.size,0);assert.equal(s.notes,'');assert.equal(s.attempts,0);assert.equal(s.bell,2);assert(!sceneState(s).collapsed);assert.equal(sceneState(s).burned,i>0);assert.equal(sceneState(s).memorial,i>1);}assert(!sceneState(createState(0)).body);});
test('pause freezes all event state',()=>{const s=createState(2,{tutorial:false});beginNight(s);advance(s,5);s.paused=true;const snapshot=structuredClone(s);advance(s,30);assert.deepEqual(s,snapshot);});
test('133 unique Hebrew lines have exact subtitle/filename and recording metadata',()=>{assert.equal(VOICES.length,133);assert.equal(new Set(VOICES.map(v=>v.id)).size,133);for(const v of VOICES){assert.match(v.text,/[א-ת]/);assert.equal(v.file,`assets/voices/${v.id}.mp3`);assert.equal(LINE[v.id].text,v.text);assert(v.direction&&v.context&&v.character);assert.equal(typeof v.essential,'boolean');}for(const r of RESIDENTS){assert.equal(VOICES.filter(v=>v.resident===r.id).length,19);for(const field of ['obsession','secret','relationship','behavior','activity','direction'])assert(r[field]);}});
test('all clues and proof groups resolve to real case locations, with four independent groups',()=>{for(const c of CASES){const ids=new Set(c.clues.map(x=>x.id));assert.equal(ids.size,c.clues.length);assert.equal(c.reconstruction.length,3);assert.equal(c.hints.length,3);assert(c.clues.some(x=>x.kind==='testimony'));assert(c.clues.some(x=>x.kind==='document'));for(const group of c.proofGroups)for(const id of group)assert(ids.has(id));for(const cl of c.clues)assert([...LOCATIONS,...RESIDENTS].some(x=>x.id===cl.location));}});
