import {test,expect} from '@playwright/test';
import {startCreatorServer} from '../../tools/creator/server.mjs';
import {creatorCatalogue} from '../../tools/creator/catalogue.mjs';
import {readLibrary,sha256} from '../../tools/creator/storage.mjs';
import {mkdtemp,mkdir,readFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {wav} from '../browser/dubbing-helpers.mjs';
const catalogue=creatorCatalogue();let app,voiceRoot,failCommit=false;
function clicks(){const bytes=wav(5),rate=16000;for(let i=0;i<rate*5;i++){const time=i/rate;let value=time>.5&&time<4.5?Math.sin(time*2*Math.PI*220)*7000:0;if((time>.055&&time<.057)||(time>4.945&&time<4.947))value=30000*Math.sin(time*2*Math.PI*2000);bytes.writeInt16LE(Math.round(value),44+i*2);}return bytes;}
async function seed(id,bytes=clicks()){const line=catalogue.lines.find(l=>l.id===id);return app.library.save({lineId:id,takeId:randomUUID(),expectedTakeId:null,scriptVersion:line.scriptVersion,fingerprint:line.fingerprint,performanceKey:line.performanceKey,validation:{hasSignal:true,duration:5,peak:.95}},{type:'audio/wav',bytes},{type:'audio/wav',bytes});}
test.beforeAll(async()=>{await mkdir('.cache',{recursive:true});voiceRoot=await mkdtemp(resolve('.cache/creator-editing-'));app=await startCreatorServer({port:4176,voiceRoot,catalogue:async()=>catalogue,beforeCommit:()=>{if(failCommit)throw Error('SYNTHETIC failed edit save');}});});
test.afterAll(async()=>app.close());
async function open(page,id){page.on('dialog',d=>d.accept());await page.goto('/creator/');await page.locator('#filter').selectOption('all');await page.locator('#group').selectOption('all');await page.locator(`[data-character="${id.split('.')[0]}"]`).click();await page.locator(`[data-line="${id}"]`).click();}
async function hearPart(page,button='#listen'){await page.locator(button).click();await expect(page.locator('#stop-listening')).toBeEnabled();await expect.poll(()=>page.evaluate(async()=>(await import('/src/speech-animation.js')).speech.mouth),{intervals:[40,60]}).toBeGreaterThan(0);await page.locator('#stop-listening').click();await expect(page.locator('#stop-listening')).toBeDisabled();expect(await page.evaluate(async()=>(await import('/src/speech-animation.js')).speech.mouth)).toBe(0);}
async function inspectDraft(page,id='goat.greet'){return page.evaluate(async id=>{const {drafts}=await import('/creator/drafts.js'),d=await drafts.get(id),ctx=new OfflineAudioContext(1,1,48000),buffer=await ctx.decodeAudioData(await d.blob.arrayBuffer()),samples=buffer.getChannelData(0),digest=async blob=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer())),x=>x.toString(16).padStart(2,'0')).join('');let peak=0;for(const v of samples)peak=Math.max(peak,Math.abs(v));return {duration:buffer.duration,first:samples[0],last:samples.at(-1),peak,sha:await digest(d.blob),sourceSha:await digest(d.source),takeId:d.takeId,reviewed:d.reviewed,processing:d.processing};},id);}
test('partial listening; trim saved take removes synthetic clicks, survives reload and publishes exact preview; reset is non-destructive',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const original=await seed('goat.greet');await open(page,'goat.greet');await hearPart(page,'#listen-saved');await expect(page.locator('#edit-saved')).toBeEnabled();
 await page.locator('#edit-saved').click();await expect(page.locator('#trim-editor')).toBeVisible();await expect(page.locator('#listen')).toBeEnabled();
 await page.locator('#trim-start').fill('0.2');await page.locator('#trim-end').fill('0.2');await expect(page.locator('#listen')).toBeDisabled();await page.locator('#apply-trim').click();await expect(page.locator('#record-status')).toContainText('החיתוך הוחל');await expect(page.locator('#save-next')).toBeDisabled();
 const trimmed=await inspectDraft(page);expect(trimmed.duration).toBeCloseTo(4.6,3);expect(trimmed.peak).toBeLessThan(.22);expect(trimmed.first).toBe(0);expect(trimmed.last).toBe(0);expect(trimmed.sourceSha).toBe(original.sourceSha256);expect((await readLibrary(voiceRoot)).entries['goat.greet'].takeId).toBe(original.takeId);
 await page.reload();await expect(page.locator('#trim-start')).toHaveValue('0.2');await expect(page.locator('#trim-end')).toHaveValue('0.2');await hearPart(page);await expect(page.locator('#save-next')).toBeEnabled();await page.locator('#save-next').click();await expect(page.locator('#record-status')).toContainText('נשמר בפרויקט');
 const saved=(await readLibrary(voiceRoot)).entries['goat.greet'];expect(saved.processing.trim).toMatchObject({start:.2,end:.2,sourceDuration:5,fadeSeconds:.005});expect(saved.sha256).toBe(trimmed.sha);expect(saved.sourceSha256).toBe(original.sourceSha256);expect(sha256(await readFile(join(voiceRoot,saved.file)))).toBe(trimmed.sha);
 const mapping=await (await page.request.get('/assets/voices/available.json')).json();expect(mapping['goat.greet'].file).toBe('assets/voices/'+saved.file);
 // Reopen a saved trim from its ORIGINAL source; adjustments do not accumulate.
 await page.locator('[data-line="goat.greet"]').click();await page.locator('#edit-saved').click();await expect(page.locator('#trim-end')).toHaveValue('0.2');await page.locator('#trim-end').fill('0.3');await page.locator('#apply-trim').click();await expect(page.locator('#record-status')).toContainText('החיתוך הוחל');expect((await inspectDraft(page)).duration).toBeCloseTo(4.5,3);
 await page.locator('#trim-end').fill('0.1');await page.locator('#apply-trim').click();await expect(page.locator('#record-status')).toContainText('החיתוך הוחל');expect((await inspectDraft(page)).duration).toBeCloseTo(4.7,3);
 await page.locator('#reset-trim').click();await expect(page.locator('#record-status')).toContainText('החיתוך בוטל');expect((await inspectDraft(page)).sha).toBe(original.sha256);
 await page.locator('#trim-start').fill('4.99');await page.locator('#apply-trim').click();await expect(page.locator('#record-status')).toContainText('החיתוך גדול מדי');expect((await inspectDraft(page)).sha).toBe(original.sha256);
 await page.locator('#reset-trim').click();await expect(page.locator('#record-status')).toContainText('החיתוך בוטל');await page.locator('#trim-tail').click();await expect(page.locator('#record-status')).toContainText('החיתוך הוחל');expect((await inspectDraft(page)).duration).toBeCloseTo(4.8,3);
 await hearPart(page);failCommit=true;await page.locator('#save-next').click();await expect(page.locator('#record-status')).toContainText('ניסיון נוסף');expect((await readLibrary(voiceRoot)).entries['goat.greet'].takeId).toBe(saved.takeId);failCommit=false;await page.locator('#save-next').click();await expect(page.locator('#record-status')).toContainText('נשמר בפרויקט');expect(errors).toEqual([]);
});
test('stopping before audio starts never falsely approves a draft',async({page})=>{
 await seed('snake.greet');await page.addInitScript(()=>{HTMLMediaElement.prototype.play=function(){return new Promise(()=>{});};});await open(page,'snake.greet');await page.locator('#edit-saved').click();await expect(page.locator('#listen')).toBeEnabled();await page.locator('#listen').click();await page.locator('#stop-listening').click();await expect(page.locator('#save-next')).toBeDisabled();await expect(page.locator('#listen')).toBeEnabled();await expect(page.locator('#record-status')).toContainText('לפני שהקול התחיל');
});
test('synthetic capture requests noise suppression without AGC; edited output retains untouched capture',async({page})=>{
 await page.addInitScript(()=>{const get=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=options=>{window.creatorCaptureOptions=options;return get(options);};});await open(page,'boar.greet');await page.locator('#noise-reduction').check();await page.locator('#record').click();await expect(page.locator('#stop')).toBeEnabled();await expect.poll(()=>page.locator('#input-level').evaluate(e=>e.value)).toBeGreaterThan(.05);await page.waitForTimeout(1000);await page.locator('#stop').click();await expect(page.locator('#listen')).toBeEnabled();expect(await page.evaluate(()=>window.creatorCaptureOptions.audio)).toMatchObject({noiseSuppression:true,autoGainControl:false});
 const full=await inspectDraft(page,'boar.greet');await page.locator('#trim-tail').click();await expect(page.locator('#record-status')).toContainText('החיתוך הוחל');const shortened=await inspectDraft(page,'boar.greet');expect(shortened.duration).toBeCloseTo(full.duration-.2,3);expect(shortened.sourceSha).toBe(full.sourceSha);expect(shortened.processing.enhance).toBe(true);expect(shortened.processing.autoGainControl).toBe(false);
 await page.locator('#reset-trim').click();await expect(page.locator('#record-status')).toContainText('החיתוך בוטל');expect((await inspectDraft(page,'boar.greet')).sha).toBe(full.sha);
});
