import {CASES,RESIDENTS,SUPPORTING,LOCATIONS} from './content.js';
import {InvestigationSave} from './investigation-save.js';
import {createState,update,record,inspect,inspectPreliminary,intervene,evaluate,beginNight,acknowledgeCrime,startReconstruction,reconstructionStep,timeLabel} from './simulation.js';
import {PHASES,guidance,phaseIndex,tutorialEvent,tutorialBlocking,skipTutorial,accusationRequirements} from './progression.js';
import {render,hitTest,hitCandidates,portrait,renderPortraits} from './render.js';
import {TargetPicker} from './target-picker.js';
import {TutorialOverlay} from './tutorial-overlay.js';
import {AudioManager} from './audio.js';
import {VoiceStore} from './voice-store.js';
import {QuickDubbing} from './quick-dubbing.js';
import {siteLinks} from './site-links.js';
import {QUICK_ROLES,roleManifest,dialogueLine} from './dialogue-manifest.js';
import {loadArt} from './art-assets.js';
import {sceneState} from './incidents.js';
import {frameSteps} from './timing.js';
import {isSandboxOrigin} from './paid-environment.js';
if(isSandboxOrigin(location.origin)){
 const notice=document.createElement('div');notice.className='sandbox-notice';notice.setAttribute('role','note');notice.textContent='סביבת בדיקות · תשלום מדומה בלבד · השתמשו בכרטיס בדיקה';document.body.prepend(notice);
 document.title='זובלוף — סביבת בדיקות';
}
const artReady=loadArt();
const $=id=>document.getElementById(id),canvas=$('world');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// A named, isolated browser-test profile never clears the player's real save.
const testProfile=new URLSearchParams(location.search).get('test-profile');
// Keep the original storage key so the rename preserves existing progress.
const storageKey=testProfile?`neighborhood-test-${testProfile}`:'neighborhood-animals-dark-v2';
let state=createState(),modalOpen=false,started=false,lastFrame=0,lastSerial=-1,selected=null,chosen=new Set(),returnFocus=null,toastTimer,reconSegment=-1,noticeId=null,notebookSection='case',stuckTime=0,hintOffered=false;
const picker=new TargetPicker(selectTarget),coach=new TutorialOverlay({canvas,getState:()=>state,isModal:()=>modalOpen||!started,onSkip:skipTraining});
let progress={completed:{},tutorialDone:false,settings:{sound:true,music:true,subtitles:true}};
try{const p=JSON.parse(localStorage.getItem(storageKey));if(p&&p.completed)progress={...progress,...p,settings:{...progress.settings,...p.settings}};}catch{}
const investigationStorage={getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)};
const investigation=new InvestigationSave(investigationStorage,storageKey+':active',()=>toast('לא הצלחנו לשמור את החקירה במכשיר. השמירה הקודמת נשארה; פנו מקום ונסו שוב.'));
let noteSaveTimer,checkpointTimer=0,lastCheckpointSignature='';
function persistInvestigation(){if(!started)return;clearTimeout(noteSaveTimer);investigation.write(state,{selected,chosen:[...chosen],notebookSection,casting:[...(audio.personalCharacters||[])]});}
let spokenGuide=null,dubbing=null,earlyLines=[],earlyElapsed=0;
const audio=new AudioManager(line=>{spokenGuide=line?.resident==='guide'?line:null;const show=line&&!modalOpen&&!spokenGuide;$('subtitle').style.display=show?'block':'none';$('subtitle').innerHTML=show?`<strong>${line.character}</strong>${line.text}`:'';if(started)refresh();});audio.settings=progress.settings;
const voices=new VoiceStore({name:testProfile?`neighborhood-voices-test-${testProfile}`:undefined,onWarning:toast});audio.store=voices;
dubbing=new QuickDubbing({store:voices,audio,openDialog,getActive:()=>audio.personalCharacters?.size>1?[...audio.personalCharacters]:audio.personalCharacter||null,onStart:(index,active,options)=>{if(options.resume){const ids=Array.isArray(active)?active:active?[active]:[];if(ids.length&&ids.every(id=>voices.coverage(CASES[index].id,id).complete))audio.repairNeeded?.clear();closeDialog();return;}progress.caseCasting=audio.configureCase(CASES[index].id,active);delete progress.voiceCharacter;save();launchCase(index,options);}});
window.addEventListener('zoobluff-account-changed',()=>{audio.stop();if(started){audio.configureCase(state.case.id,null,{resume:true});persistInvestigation();refresh();}});
audio.onPersonalFailure=()=>{toast('הקול האישי לא נטען. ממשיכים בכתוביות; אפשר לתקן אחרי השיחה.');};
const repairButton=document.createElement('button');repairButton.id='repair-voice';repairButton.textContent='תיקון הקול האישי';repairButton.hidden=true;repairButton.onclick=()=>dubbing.open(state.index,{resume:true,repair:true});document.querySelector('.header-actions').append(repairButton);
function save(){try{localStorage.setItem(storageKey,JSON.stringify(progress));}catch{toast('השמירה אינה זמינה בדפדפן. אפשר להמשיך לשחק.');}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),5000);}
function openDialog(title,body,wide=false){picker.close(false);dubbing?.disposeView();if(!modalOpen)returnFocus=document.activeElement;modalOpen=true;audio.stop();$('app').inert=true;$('overlay').hidden=false;$('dialog').className=wide?'wide':'';$('dialog').innerHTML=`<div class="dialog-top"><h2 id="dialog-title">${title}</h2><button id="close-dialog" aria-label="סגירה">×</button></div>${body}`;$('close-dialog').onclick=()=>started?closeDialog():welcome();$('dialog').focus();$('dialog').scrollTop=0;renderPortraits();}
function closeDialog(){const completedNotebook=state.tutorial.enabled&&state.tutorial.step==='notebook-return';dubbing?.disposeView();if(state.tutorial.step==='notebook-entry')state.tutorial.step='notebook-before';else if(state.tutorial.step==='ask-witness')state.tutorial.step='witness';else{tutorialEvent(state,'notebook-closed');tutorialEvent(state,'dialog-closed');}modalOpen=false;$('app').inert=false;$('overlay').hidden=true;audio.stop();if(state.flow==='accuse')state.flow='investigate';if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else canvas.focus({preventScroll:true});refresh();if(completedNotebook)audio.speak('observed');}
function startCase(index,options={}){audio.unlock();dubbing.open(index,options);}
function launchCase(index,{tutorial=index===0&&!progress.tutorialDone}={}){
 audio.unlock();audio.stop();clearTimeout(toastTimer);$('toast').classList.remove('visible');$('toast').textContent='';investigation.begin();state=createState(index,{tutorial});lastSerial=-1;selected=null;chosen.clear();started=true;reconSegment=-1;noticeId=null;notebookSection='case';stuckTime=0;hintOffered=false;$('finding').hidden=true;closeDialog();
 earlyLines=[...new Set([...(audio.personalCharacters||[]),QUICK_ROLES[state.case.id]].filter(id=>id!=='guide'))].map(id=>dialogueLine(state.case.id,id,'encounter'));earlyElapsed=0;audio.cooldowns.clear();
 record(state,'תחילת המשמרת. הלילה יתחיל רק כשנבחר לסיים את התצפית.','tutorial','17:00');
 openDialog(`תיק ${index+1} · ${state.case.title}`,`<p>${state.case.brief}</p><p class="dialog-intro">אתם משמרת השכונה. הכירו את השכנים, בדקו מה משתנה, וחברו ראיות. הלילה מתחיל רק כשתבחרו להתקדם.</p><div class="dialog-buttons"><button class="primary" id="begin-case">${tutorial?'להכיר את ירחמיאל':'לצאת לשכונה'}</button>${tutorial?'<button id="skip-intro">משחק ללא הדרכה</button>':''}</div>`);
 $('begin-case').onclick=()=>{closeDialog();if(tutorial)audio.speak('role');else document.querySelector('.world-column').scrollIntoView({block:'start',behavior:'smooth'});};if($('skip-intro'))$('skip-intro').onclick=()=>{skipTutorial(state);closeDialog();};refresh();
}
async function resumeInvestigation(){
 const saved=investigation.resume();if(saved.status!=='ready'){toast('השמירה אינה ניתנת לקריאה. היא נשמרה ללא שינוי.');return;}
 audio.unlock();await voices.ready;let casting=saved.ui.casting;
 if(casting.length&&!await dubbing.access.check()){casting=[];toast('החקירה נשמרה. כדי להמשיך בקולות האישיים, התחברו לחשבון שרכש.');}
 dubbing.disposeView();audio.stop();state=saved.state;selected=saved.ui.selected;chosen=new Set(saved.ui.chosen);notebookSection=saved.ui.notebookSection;started=true;lastFrame=performance.now();lastSerial=-1;noticeId=state.lastFinding?.id;reconSegment=Math.min(2,Math.floor(state.reconTime/6));earlyLines=[];earlyElapsed=0;
 audio.configureCase(state.case.id,casting,{resume:true});modalOpen=false;$('app').inert=false;$('overlay').hidden=true;$('finding').hidden=true;canvas.focus();refresh();
 const step=state.tutorial.step;if(state.flow==='accuse')accusation();else if(state.flow==='result')result();else if(['notebook-entry','notebook-return'].includes(step))notebook();else if(step==='prefact-return')locationDialog(state.case.preLocation);else if(step==='trace-return')locationDialog(state.case.source);else if(['ask-witness','witness-return'].includes(step))residentDialog('goat');
 audio.stop();persistInvestigation();
}
function welcome(){const saved=investigation.read();openDialog('זובלוף',`<div class="hero-kicker">משמרת ראשונה בנווה־בערך</div><h2 class="hero-title">רחוב יפה.<br>אנשים קשים.</h2><div class="hero-art">${RESIDENTS.map(portrait).join('')}</div><p>הכירו את השכנים, צפו במה שהם עושים, ואז עברו ללילה וגלו מה השתנה.</p><p class="dialog-intro">הצעד הבא מופיע מעל השכונה. מחברת החקירה תמיד זמינה בתחתית המסך.</p><div class="dialog-buttons">${saved.status==='ready'?'<button id="continue-investigation" class="primary">המשך חקירה</button>':''}<button id="start" class="${saved.status==='ready'?'':'primary'}">${saved.status==='ready'?'להתחיל חקירה חדשה':'להתחיל לחקור'}</button><button id="choose-start">בחירת תיק</button></div>${saved.status==='damaged'?'<p role="alert">השמירה הקודמת אינה ניתנת לקריאה. לא מחקנו אותה. התחלת תיק חדש תשמור עותק שלה במכשיר.</p>':''}${siteLinks}`);if($('continue-investigation'))$('continue-investigation').onclick=resumeInvestigation;$('close-dialog').hidden=true;$('start').onclick=()=>startCase(Math.max(0,CASES.findIndex(c=>!progress.completed[c.id])));$('choose-start').onclick=caseSelection;}
function caseSelection(){openDialog('תיקי השכונה',`<p class="dialog-intro">שלושה תיקים עוקבים. בחירה בתיק משחזרת את מצב השכונה בתחילתו. בכל תיק אתם בוחרים מתי לסיים את התצפית ולעבור ללילה.</p><div class="case-grid">${CASES.map((c,i)=>`<button class="case-choice" data-case="${i}"><span class="num">0${i+1}</span><span><h3>${c.title} ${progress.completed[c.id]?'<span class="badge">פוענח</span>':''}</h3><p>${c.subtitle}</p></span></button>`).join('')}</div>`);if(!started)$('close-dialog').onclick=welcome;document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>startCase(Number(b.dataset.case)));}
function availableWorld(){return started&&!['night','discovery'].includes(state.flow)&&!state.reconstructing;}
function selectTarget(target){state.selection=target;target.type==='resident'?residentDialog(target.id):target.type==='support'?supportingDialog(target.id):locationDialog(target.id);}
function skipTraining(){skipTutorial(state);picker.close();down=null;progress.tutorialDone=true;save();audio.stop();toast('ההדרכה דולגה. אפשר להמשיך לצפות או לעבור ללילה.');refresh();coach.update();}
function evidenceAt(id,event='evidence'){const found=inspect(state,id);if(state.case.clues.some(c=>c.location===id&&state.clues.has(c.id)))tutorialEvent(state,event,id);if(found.length){audio.tone(660,.2);stuckTime=0;hintOffered=false;}refresh();return found;}
function supportingDialog(id,event){
 if(!availableWorld())return;
 const alive=id===QUICK_ROLES[state.case.id]&&!(state.case.id==='courtyard'&&state.crimeDone);
 if(!alive){locationDialog(id==='badger'?'garden':'home');return;}
 state.selection={type:'support',id};
 const selectedEvent=event||(state.crimeDone?'aftermath':'intro'),line=dialogueLine(state.case.id,id,selectedEvent);state.conversations??=new Set();state.conversations.add(id+':'+selectedEvent);
 const options=state.case.id==='fire'?(state.crimeDone?['care','copies','receipt']:['notice','copies','receipt']):state.case.id==='courtyard'?['notice','copies','receipt','chair']:state.crimeDone?['pause','space']:['notice','queue','pause'];
 const labels={notice:'מה כדאי לבדוק בשכונה?',copies:'איך בודקים רישום?',receipt:'ומה עם קבלה מקומטת?',chair:'אפשר לשבת לידך?',care:'איך אפשר לעזור לשכנים?',queue:'איך הלך בוועד?',pause:'רוצה רגע של שקט?',space:'איך אפשר לעזור?'};
 openDialog(line.character,`<div class="supporting-profile">${portrait({id,name:line.character})}<div><p>${roleManifest(state.case.id,id).description}</p><div class="speech">״${line.text}״</div></div></div><div class="question-options">${options.map(key=>`<button data-support-event="${key}">${labels[key]}</button>`).join('')}</div><div class="dialog-buttons"><button id="support-back" class="primary">חזרה לשכונה</button>${!state.crimeDone?'<button id="support-notice">לבדוק את לוח ההודעות</button>':''}</div>`);audio.speak(selectedEvent,id);$('support-back').onclick=closeDialog;
 document.querySelectorAll('[data-support-event]').forEach(b=>b.onclick=()=>supportingDialog(id,b.dataset.supportEvent));if($('support-notice'))$('support-notice').onclick=()=>locationDialog(state.case.preLocation);
}
function locationDialog(id){
 if(!availableWorld())return;state.selection={type:'location',id};const place=LOCATIONS.find(l=>l.id===id);let body=`<span class="eyebrow">בדיקת מקום · ${place.name}</span>`;
 if(!state.crimeDone){const added=inspectPreliminary(state,id);body+=`<p${id===state.case.preLocation?' id="preliminary-notice"':''}>${id===state.case.preLocation?state.case.preFact:place.description}</p>${added?'<p class="inline-success">✓ התצפית נוספה למחברת החקירה.</p>':''}<p class="dialog-intro">אפשר להמשיך לצפות. המעבר ללילה מתבצע רק בכפתור המתאים.</p>`;}
 else{evidenceAt(id);const clues=state.case.clues.filter(c=>c.location===id&&state.clues.has(c.id));body+=clues.length?`<div class="clue-list">${clues.map(clueCard).join('')}</div>`:'<p>אין כאן ממצא חדש. בדקו נצנוץ אחר או שאלו שכן מה ראה.</p>';}
 const v=sceneState(state),asset=id==='home'?(v.collapsed?'home-collapsed':v.burned?'home-burned':null):id==='garden'&&v.body?'courtyard-evidence':null;
 if(asset)body=`<figure class="scene-detail"><img src="assets/art/${asset}.webp" alt="תקריב הזירה: ${place.name}"><figcaption>${id==='home'?'הנזק נשאר. הבדיקה נעשית מחוץ לשטח הסגור.':'עמוס, גירית בוגר, נמצא מת. הזירה סגורה לבדיקה.'}</figcaption></figure>`+body;
 if(id==='home'&&state.index>0)body+='<p class="continuity-note">הפיח הוא מן השרפה בתיק הקודם. הדיירים עדיין בדיור זמני.</p>';
 const support=id==='garden'&&(state.index===0||state.index===1&&!state.crimeDone)?'badger':state.index===2&&id==='home'?'hedgehog':null;
 body+=`<div class="dialog-buttons"><button id="back-world" class="primary">חזרה לשכונה</button><button id="entry-notebook">לראות במחברת</button>${support?`<button id="meet-support">${support==='badger'?'לדבר עם עמוס':'לדבר עם רינה'}</button>`:''}</div>`;openDialog(place.name,body);$('back-world').onclick=closeDialog;$('entry-notebook').onclick=()=>notebook(state.crimeDone?'evidence':'case');if(support)$('meet-support').onclick=()=>supportingDialog(support);refresh();
}
function currentActivity(id){const r=state.residents.find(r=>r.id===id);return r.watched?r.behavior:r.carry?'נושא חפץ בין המקומות':r.route.length?'בדרך למקום אחר בשכונה':r.activity;}
function residentDialog(id,event){
 if(!availableWorld())return;state.selection={type:'resident',id};tutorialEvent(state,'resident',id);const r=RESIDENTS.find(r=>r.id===id),selectedEvent=event||(state.crimeDone?'aftermath':'intro'),line=dialogueLine(state.case.id,id,selectedEvent);state.conversations??=new Set();state.conversations.add(id+':'+selectedEvent);
 openDialog(r.name,`<div class="profile">${portrait(r)}<div><strong>${r.role}</strong><p>${currentActivity(id)}</p></div></div><div class="speech">״${line.text}״</div><div class="question-options">${state.crimeDone?'<button data-question="alibi">איפה היית בזמן שזה קרה?</button><button data-question="detail">מה עוד ראית או שמעת?</button>':''}<button data-question="secret">מה הסיפור שלך בשכונה?</button><button id="physical">להסתכל מקרוב</button></div><p class="dialog-intro">הזמן נעצר בזמן השיחה. הדברים שנאמרים הם עדות, ולא הוכחה בפני עצמם.</p><div class="dialog-buttons"><button class="primary" id="leave-person">חזרה לשכונה</button></div>`);audio.speak(selectedEvent,id);
 const flavors=document.createElement('div');flavors.className='question-options optional-talk';flavors.innerHTML='<details><summary>עוד רגע עם השכן · שיחה ללא ראיות</summary><button data-flavor="complaint">איך החיים בשכונה?</button><button data-flavor="boast">במה אתם גאים?</button><button data-flavor="question">אפשר לשאול משהו?</button><button data-flavor="encounter">שלום לשכן</button></details>';$('dialog').querySelector('.question-options').after(flavors);flavors.querySelectorAll('[data-flavor]').forEach(b=>b.onclick=()=>residentDialog(id,b.dataset.flavor));
 document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{const q=b.dataset.question;if(q!=='secret'&&state.crimeDone)evidenceAt(id,'testimony');residentDialog(id,q);});
 $('physical').onclick=()=>{const found=evidenceAt(id,'testimony');openDialog(`מבט מקרוב · ${r.name}`,`<p>${r.obsession+' '+r.relationship}</p>${found.map(clueCard).join('')}<div class="dialog-buttons"><button id="back-person">להמשיך לדבר</button><button id="leave-person" class="primary">חזרה לשכונה</button></div>`);$('back-person').onclick=()=>residentDialog(id);$('leave-person').onclick=closeDialog;};$('leave-person').onclick=closeDialog;refresh();
}
const clueKind=c=>({trace:'ממצא שנבדק',document:'מסמך שנמצא',testimony:'דברי שכן · טרם אומתו',intervention:'ממצא בעקבות פעולה',observation:'תצפית לפני האירוע'}[c.kind]);
const foundWhere=c=>LOCATIONS.find(l=>l.id===c.location)?.name||RESIDENTS.find(r=>r.id===c.location)?.name||'השכונה';
function clueCard(c){return `<article class="clue-card" id="entry-${c.id}"><small>${clueKind(c)} · ${foundWhere(c)} · <bdi>${c.time}</bdi></small><strong>${c.title}</strong><p>${c.text}</p><small>${c.kind==='testimony'?'השוו את הגרסה לממצאים ולשעות שנרשמו.':'אפשר להשוות את הפרט הזה לעדויות ולממצאים ממקומות אחרים.'}</small></article>`;}
function notebook(section=notebookSection,entryId){
 if(state.tutorial.enabled&&['notebook-before','notebook-entry','notebook-return'].includes(state.tutorial.step)){section='case';entryId=state.tutorial.observationId;}
 if(!started)return;notebookSection=section;tutorialEvent(state,'notebook');state.unread.clear();$('finding').hidden=true;noticeId=state.lastFinding?.id;
 const tabs=[['case','התיק'],['evidence','ראיות'],['people','שכנים ועדויות'],['timeline','ציר זמן'],['accusation','האשמה']];let body='';
 if(section==='case')body=`<h3>${state.case.title}</h3><p>${state.crimeDone?state.case.consequence:state.case.brief}</p><article class="clue-card"><strong>הצעד הבא</strong><p>${guidance(state).text}</p></article><h3>תצפיות ראשוניות</h3>${state.preliminary.map(clueCard).join('')||'<p>בדקו מקום בשלב התצפית כדי לתעד מה היה כאן לפני האירוע.</p>'}<details class="personal-notes"><summary>החשדות והמחשבות שלי</summary><p class="dialog-intro">פרשנות שלכם בלבד. אינה נחשבת ראיה.</p><textarea maxlength="100000" id="notes" placeholder="מה עדיין לא מסתדר?">${esc(state.notes)}</textarea></details>`;
 if(section==='evidence')body=`<p class="dialog-intro">ממצאים ומסמכים שנבדקו. דברי השכנים נמצאים בלשונית העדויות.</p><div class="clue-list">${state.case.clues.filter(c=>state.clues.has(c.id)&&c.kind!=='testimony').map(clueCard).join('')||'<div class="empty">עדיין אין ממצאים. אחרי המעבר ללילה, בדקו את הנצנוצים ליד המקומות.</div>'}</div>`;
 if(section==='people')body=`<p class="dialog-intro">העדות היא גרסת השכן. זהות הדובר אינה הופכת אותה לעובדה.</p><div class="people-list">${RESIDENTS.map(r=>`<article class="person-entry"><div class="profile">${portrait(r)}<div><strong>${r.name}</strong><p>${r.role}</p><button data-talk="${r.id}" ${availableWorld()?'':'disabled'}>לדבר עם ${r.name}</button></div></div>${state.case.clues.filter(c=>c.location===r.id&&state.clues.has(c.id)).map(clueCard).join('')}</article>`).join('')}</div>`;
 if(section==='timeline')body=`<p class="dialog-intro">אירועים, פעולות ותצפיות — בלי מסקנה אוטומטית.</p><div class="clue-list">${[...state.events].reverse().map(e=>`<article class="clue-card"><small><bdi>${esc(e.time)}</bdi> · ${e.kind==='intervention'?'פעולה שלכם':'רישום'}</small><p>${esc(e.text)}</p></article>`).join('')}</div>`;
 if(section==='accusation')body=`<h3>איך בונים הסבר?</h3><p>בחרו חשוד, ואז ארבע ראיות שמחברות אותו למעשה. לא צריך לאסוף כל פרט בשכונה.</p><p class="inline-success">${accusationRequirements(state)||`יש לכם ${state.clues.size} ראיות. אפשר לבנות האשמה כעת.`}</p><button id="notebook-accuse" class="primary">בחירת חשוד וראיות</button><p class="dialog-intro">אם ההסבר אינו מתאים, תקבלו משוב ותוכלו לנסות שוב.</p>`;
 if(section==='case'){const observations=(state.observations||[]).map(o=>`<details class="clue-card observation-entry" id="entry-${o.id}"><summary>${o.title} · ${o.time}</summary><p>${o.text}</p></details>`).join('');body=observations+(state.tutorial.enabled&&['notebook-entry','notebook-return'].includes(state.tutorial.step)?'':body);}
 openDialog('מחברת החקירה',`<nav class="note-tabs" aria-label="מדורי המחברת">${tabs.map(([id,label])=>`<button data-note="${id}" class="${id===section?'active':''}" aria-pressed="${id===section}">${label}</button>`).join('')}</nav>${body}<div class="dialog-buttons"><button id="notebook-close" class="primary">חזרה לשכונה</button></div>`,true);
 if(state.tutorial.enabled&&['notebook-entry','notebook-return'].includes(state.tutorial.step))$('dialog').classList.add('tutorial-notebook');
 for(const entry of document.querySelectorAll('.observation-entry'))entry.addEventListener('toggle',()=>{if(entry.open){tutorialEvent(state,'entry-opened',entry.id.slice(6));refresh();}});
 document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>notebook(b.dataset.note));document.querySelectorAll('[data-talk]').forEach(b=>b.onclick=()=>residentDialog(b.dataset.talk));if($('notes'))$('notes').oninput=e=>{state.notes=e.target.value;clearTimeout(noteSaveTimer);noteSaveTimer=setTimeout(persistInvestigation,250);};if($('notebook-accuse'))$('notebook-accuse').onclick=accusation;$('notebook-close').onclick=closeDialog;
 if(entryId)$(`entry-${entryId}`)?.scrollIntoView({block:'center'});refresh();
}
function accusation(){
 const missing=accusationRequirements(state);if(missing){openDialog('עוד רגע לפני האשמה',`<p>${missing}</p><p>הראיות נשמרות. אין צורך לאסוף כל ממצא, אבל צריך ארבע ראיות כדי לבנות הסבר.</p><button id="requirements-back" class="primary">חזרה לחקירה</button>`);$('requirements-back').onclick=closeDialog;return;}
 state.flow='accuse';openDialog('מי עשה את זה?',`<p class="dialog-intro">בחרו חשוד וארבע ראיות. אחר כך תבדקו את ההסבר לפני השליחה.</p><fieldset class="suspect-grid"><legend>החשוד שבחרתם</legend>${RESIDENTS.map(r=>`<label class="suspect-option ${selected===r.id?'selected':''}"><input type="radio" name="suspect" data-suspect="${r.id}" value="${r.id}" ${selected===r.id?'checked':''}>${portrait(r)}<strong>${r.name}</strong></label>`).join('')}</fieldset><div class="clue-list">${state.case.clues.filter(c=>state.clues.has(c.id)).map(c=>`<article class="clue-card"><label><input type="checkbox" value="${c.id}" ${chosen.has(c.id)?'checked':''}><span><small>${clueKind(c)} · ${foundWhere(c)}</small><strong>${c.title}</strong><p>${c.text}</p></span></label></article>`).join('')}</div><p id="accuse-status" class="warning" role="status"></p><div class="dialog-buttons"><button id="review-accusation" class="primary">לבדוק את ההסבר</button><button id="keep-looking">להמשיך לחקור</button></div>`,true);
 document.querySelectorAll('[data-suspect]').forEach(b=>b.onchange=()=>{selected=b.value;document.querySelectorAll('[data-suspect]').forEach(x=>x.closest('label').classList.toggle('selected',x.checked));persistInvestigation();});document.querySelectorAll('.clue-card input').forEach(input=>input.onchange=()=>{if(input.checked&&chosen.size>=4){input.checked=false;$('accuse-status').textContent='אפשר לבחור עד ארבע ראיות. בחרו את אלה שמתחברות להסבר.';return;}input.checked?chosen.add(input.value):chosen.delete(input.value);persistInvestigation();});$('keep-looking').onclick=closeDialog;$('review-accusation').onclick=reviewAccusation;refresh();
}
function reviewAccusation(){
 if(!selected||chosen.size<4){$('accuse-status').textContent='בחרו חשוד וארבע ראיות לפני שבודקים את ההסבר.';return;}
 const suspect=RESIDENTS.find(r=>r.id===selected);openDialog('זה ההסבר שלכם?',`<div class="profile">${portrait(suspect)}<div><strong>החשוד שבחרתם: ${suspect.name}</strong><p>האם הראיות מסבירות מי פעל ומה קרה?</p></div></div><div class="clue-list">${state.case.clues.filter(c=>chosen.has(c.id)).map(clueCard).join('')}</div><p id="accuse-status" class="warning" role="status"></p><div class="dialog-buttons"><button id="submit-accusation" class="primary">להגיש את ההאשמה</button><button id="edit-accusation">לשנות את הבחירה</button><button id="keep-looking">לחזור לשכונה</button></div>`,true);
 $('edit-accusation').onclick=accusation;$('keep-looking').onclick=closeDialog;$('submit-accusation').onclick=()=>{const answer=evaluate(state,selected,[...chosen]);state.attempts++;if(answer.ok){closeDialog();startReconstruction(state);reconSegment=-1;audio.bell();document.querySelector('.world-column').scrollIntoView({behavior:'smooth',block:'start'});refresh();}else{$('accuse-status').textContent=answer.reason==='suspect'?`${suspect.name}: ״${dialogueLine(state.case.id,suspect.id,'accusation').text}״ ההסבר לא מתאים לממצאים. השוו מסמכים, שעות ועדויות; אפשר לשנות חשוד ולנסות שוב.`:'הכיוון אינו מוכח עדיין: חסרה ראיה שמחברת בין האדם, המעשה והיעד. השוו בין המקומות לעדויות, או בחרו ראיות אחרות.';audio.speak('accusation',selected);}};
}
function result(){
 state.flow='result';const rating=state.attempts===1&&state.hints===0?'עין של נץ':state.attempts<=2?'בלש עם קבלות':'בלש עם סבלנות';progress.completed[state.case.id]={rating,attempts:state.attempts,hints:state.hints};save();
 openDialog('התיק נסגר. הוויכוח לא.',`<div class="result-seal">${rating}</div><p>${state.case.closing}</p><h3>כך הראיות מתחברות</h3>${state.case.reconstruction.map(text=>`<p>${text}</p>`).join('')}<p class="dialog-intro">${state.attempts===1?'ניסיון אחד':state.attempts+' ניסיונות'} · ${state.hints===1?'רמז אחד':state.hints+' רמזים'} · ${Object.keys(progress.completed).length} מתוך 3 תיקים פוענחו</p><div class="dialog-buttons"><button id="next-case" class="primary">${state.index<2?'לתיק הבא':'כל התיקים'}</button><button id="replay">לשחק בתיק שוב</button><button id="share">שיתוף ללא ספוילרים</button></div>`);$('next-case').onclick=nextCase;$('replay').onclick=()=>startCase(state.index,{tutorial:false});$('share').onclick=async()=>{const text=`פענחתי תיק בזובלוף. הדירוג שלי: ${rating}. גם לחפים מפשע יש כאן מה להסתיר.`;try{if(navigator.share)await navigator.share({title:'זובלוף',text,url:location.href});else{await navigator.clipboard.writeText(text+' '+location.href);$('share').textContent='הועתק ללא ספוילרים';}}catch{toast('אפשר לשתף את כתובת המשחק.');}};refresh();
}
function nextCase(){state.index<2?startCase(state.index+1,{tutorial:false}):caseSelection();}
function hint(){if(!state.crimeDone){help();return;}const n=Math.min(state.hints,2);state.hints++;openDialog(`רמז ${n+1} מתוך 3`,`<p>${state.case.hints[n]}</p><p class="dialog-intro">כל ממצא חיוני נשאר זמין. אין הגבלת זמן.</p><button id="hint-back" class="primary">חזרה לשכונה</button>`);$('hint-back').onclick=closeDialog;}
function help(){const g=guidance(state);openDialog('מה עושים עכשיו?',`<p><strong>${g.text}</strong></p><p>${g.detail}</p><p class="dialog-intro">לחיצה על דמות או מקום פותחת בדיקה. גרירה מזיזה את העדשה. הזמן נעצר בזמן שיחה ועיון במחברת.</p><div class="dialog-buttons"><button id="help-back" class="primary">בחזרה למשחק</button>${state.crimeDone?'<button id="optional-hint">רמז לתיק</button>':''}<button id="replay-tutorial">הדרכה מחדש</button></div><small>הדרכה מחדש פותחת את התיק הראשון. דירוגים שכבר הושגו נשמרים.</small>`);$('help-back').onclick=closeDialog;if($('optional-hint'))$('optional-hint').onclick=hint;$('replay-tutorial').onclick=()=>startCase(0,{tutorial:true});}
function settings(){openDialog('הגדרות',`<label class="setting-row">צלילים וקולות<input id="sound-setting" type="checkbox" ${audio.settings.sound?'checked':''}></label><label class="setting-row">מוזיקת רקע<input id="music-setting" type="checkbox" ${audio.settings.music?'checked':''}></label><label class="setting-row">כתוביות לצד השכונה<input id="subtitle-setting" type="checkbox" ${audio.settings.subtitles?'checked':''}></label><p class="dialog-intro">המשחק פועל במלואו בטקסט. קולות היוצר כבר כלולים. אפשר להקליט קולות אישיים במכשיר. כיבוי הכתוביות מסתיר שיחות אווירה; טקסט החקירה וטקסט חלופי לקול חסר נשארים זמינים.</p><p class="dialog-intro">רווח: השהיה. חצים כשהמפה ממוקדת: הזזת העדשה. בטלפון: גרירה להזזה, הקשה לבדיקה. הפעמון אוסף שכנים והממטרה משנה את התנהגות השכנים; לכל אחד שתי הפעלות בתיק.</p>`);const voiceButton=document.createElement('button');voiceButton.id='manage-voice';voiceButton.textContent='הקול שלי · בחירה והקלטות';voiceButton.onclick=()=>dubbing.open(state.index,{resume:started});$('dialog').append(voiceButton);const accountButton=document.createElement('button');accountButton.id='manage-account';accountButton.textContent='החשבון שלי · הרשאה והתנתקות';accountButton.onclick=()=>dubbing.accountPanel();$('dialog').append(accountButton);for(const [key,id]of [['sound','sound-setting'],['music','music-setting'],['subtitles','subtitle-setting']])$(id).onchange=e=>{audio.settings[key]=e.target.checked;if(key==='sound'&&!e.target.checked)audio.stop();progress.settings=audio.settings;save();};}
function doNext(){const g=guidance(state);switch(g.action){case 'resume':state.paused=false;break;case 'meet':case 'witness':residentDialog('goat');break;case 'watch':{const r=state.residents.find(r=>r.id==='goat');Object.assign(state.lens,{x:r.x,y:r.y,active:true});toast('ירחמיאל תחת העדשה. צפו בשינוי התנוחה שלו.');audio.speak('watch');break;}case 'prefact':locationDialog(state.case.preLocation);break;case 'trace':locationDialog(state.case.source);break;case 'inspect':locationDialog(g.target.id);break;case 'notebook':notebook(state.crimeDone?'evidence':'case');break;case 'night':if(beginNight(state)){clearTimeout(toastTimer);$('toast').classList.remove('visible');audio.speak('night');document.querySelector('.world-column').scrollIntoView({block:'start',behavior:'smooth'});}break;case 'discover':acknowledgeCrime(state);audio.stop();break;case 'accuse':accusation();break;case 'next':nextCase();break;}refresh();}
function use(type){if(intervene(state,type)){audio.unlock();type==='bell'?audio.bell():audio.tone(180,.5,.04,'triangle');const speaker=state.selection?.type==='resident'?state.selection.id:state.residents[(state.index*2+(type==='bell'?0:1))%6].id;audio.speak(type==='bell'?'bell':'water',speaker,false);toast(type==='bell'?'הפעמון אוסף את השכנים. הפעולה נרשמה במחברת.':state.crimeDone?'הממטרה הופעלה מחוץ לזירה. אין ממצא חדש.':'הגינה נרטבה. השכנים עוקפים את המים.');}else toast(state.flow==='night'?'בזמן המעבר ללילה ממתינים לגילוי.':`כל ההפעלות של ${type==='bell'?'הפעמון':'הממטרה'} נוצלו בתיק הזה.`);refresh();}
function refresh(){
 repairButton.hidden=!audio.repairNeeded?.size||audio.busy||modalOpen;
 const s=state,g=guidance(s),p=phaseIndex(s);s.guideTarget=g.target||null;document.body.classList.toggle('is-reconstructing',s.reconstructing);if($('dock-phase').textContent!==PHASES[p][1])$('dock-phase').textContent=PHASES[p][1];
 $('case-number').textContent=`תיק שכונתי 0${s.index+1}`;$('case-title').textContent=s.case.title;$('time').textContent=timeLabel(s);$('phase').textContent=s.paused?'מושהה':PHASES[p][1];$('phase-strip').innerHTML=PHASES.map(([id,label],i)=>`<span class="${i===p?'current':i<p?'past':''}" ${i===p?'aria-current="step"':''}><b>${i+1}</b>${label}</span>`).join('');
 $('guide-objective').textContent=g.text;$('guide-detail').textContent=spokenGuide?.text||g.detail;$('guide-kicker').textContent=s.flow==='discovery'?'משהו קרה בשכונה':s.tutorial.enabled&&s.tutorial.step!=='done'?'המשמרת הראשונה שלכם':'הצעד הבא';
 for(const id of ['guide-action','next-action']){$(id).textContent=g.label;$(id).disabled=g.action==='none';}
 $('skip-tutorial').hidden=!s.tutorial.enabled||s.tutorial.step==='done'||s.flow==='night';$('night-card').hidden=s.flow!=='night'||s.nightElapsed>2.5;$('objective').textContent=g.text;$('brief').textContent=s.crimeDone?s.case.consequence:s.case.brief;$('clue-count').textContent=s.clues.size;$('unread-count').hidden=!s.unread.size;$('unread-count').textContent=s.unread.size;$('notebook').setAttribute('aria-label',`מחברת החקירה${s.unread.size?s.unread.size===1?', פריט חדש אחד':`, ${s.unread.size} פריטים חדשים`:''}`);
 $('pause').textContent=s.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s.paused?'המשך':'השהיה');$('speed').textContent=`×${s.speed}`;$('lens').textContent=s.lens.active?'הנחת עדשה':'הרמת עדשה';
 $('bell').innerHTML=`♧ פעמון <b>${s.bell}</b>`;$('sprinkler').innerHTML=`⌁ ממטרה <b>${s.sprinkler}</b>`;for(const id of ['bell','sprinkler','lens','speed'])$(id).disabled=['night','discovery'].includes(s.flow)||s.reconstructing||s.solved;$('pause').disabled=s.flow==='discovery'||s.solved;document.querySelectorAll('#map-buttons button').forEach(b=>b.disabled=!availableWorld());$('accuse').disabled=['night','discovery'].includes(s.flow)||s.reconstructing||s.solved;$('accuse-requirements').textContent=accusationRequirements(s)||'אפשר לבחור חשוד וארבע ראיות.';
 $('tip').textContent=s.paused?'המשחק מושהה. לחצו ▶ להמשך.':s.reconstructing?s.case.reconstruction[Math.min(2,Math.floor(s.reconTime/6))]:s.flow==='night'?'המעבר ללילה מתקדם בעצמו. אפשר להשהות אם צריך.':s.flow==='observe'?'המעבר ללילה מחכה לכם. שיחות ועיון במחברת עוצרים את הזמן.':'נצנוץ מסמן ממצא. לחצו על שכן לשיחה; כל המידע נשמר במחברת.';
 if(lastSerial!==s.serial){lastSerial=s.serial;$('activity').innerHTML=s.events.slice(0,5).map(e=>`<li><time>${esc(e.time)}</time>${esc(e.text)}</li>`).join('');}
 if(s.lastFinding&&s.lastFinding.id!==noticeId){noticeId=s.lastFinding.id;$('finding-text').textContent=`נוסף למחברת: ${s.lastFinding.title}`;$('finding').hidden=false;}
 if(s.tutorial.enabled&&s.tutorial.step==='done'&&!progress.tutorialDone){progress.tutorialDone=true;save();}
 $('guide-action').classList.toggle('pulse-once',s.flow==='discovery');document.body.classList.toggle('has-discovery',s.flow==='discovery');
}
let down=null;const position=e=>{const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left)/b.width*1000,y:(e.clientY-b.top)/b.height*760};};
function placeLens(p){const r=state.residents.find(r=>r.id==='goat');if(coach.worldTarget()?.id==='goat'&&hitCandidates(state,p,canvas.clientWidth).some(h=>h.type==='resident'&&h.id==='goat'))p={x:r.x,y:r.y-35};Object.assign(state.lens,p);if(Math.hypot(p.x-r.x,p.y-r.y)<state.lens.radius)tutorialEvent(state,'lens-placed','goat');}
canvas.onpointerdown=e=>{if(!availableWorld()||modalOpen||picker.opened)return;audio.unlock();down={...position(e),pointerId:e.pointerId,lens:state.lens.active};canvas.setPointerCapture(e.pointerId);if(state.lens.active)placeLens(position(e));};
canvas.onpointermove=e=>{if(!availableWorld()||modalOpen||picker.opened)return;if(state.lens.active&&down)placeLens(position(e));if(e.pointerType==='mouse')state.hover=hitTest(state,position(e),canvas.clientWidth);};canvas.onpointerleave=()=>state.hover=null;
canvas.onpointerup=e=>{if(!down)return;const p=position(e),tap=Math.hypot(p.x-down.x,p.y-down.y)<18,lens=down.lens;down=null;if(lens||state.lens.active)return;if(tap){const hits=hitCandidates(state,p,canvas.getBoundingClientRect().width),explicit=coach.worldTarget();if(tutorialBlocking(state)){const hit=explicit&&hits.find(h=>h.id===explicit.id&&h.type===explicit.type);if(hit)selectTarget(hit);return;}if(hits.length===1)selectTarget(hits[0]);else if(hits.length>1)picker.open(hits,{x:e.clientX,y:e.clientY},state);}};canvas.onpointercancel=()=>down=null;
canvas.onkeydown=e=>{if(!availableWorld()||modalOpen||picker.opened)return;if(e.key==='Enter'){const target=coach.worldTarget();if(target){e.preventDefault();if(['place-lens','watch'].includes(state.tutorial.step)){const r=state.residents.find(r=>r.id===target.id);state.lens.active=true;placeLens({x:r.x,y:r.y});}else selectTarget(target);refresh();persistInvestigation();return;}}const moves={ArrowLeft:[-25,0],ArrowRight:[25,0],ArrowUp:[0,-25],ArrowDown:[0,25]};if(moves[e.key]){e.preventDefault();if(tutorialBlocking(state)&&!['place-lens','watch'].includes(state.tutorial.step))return;state.lens.active=true;placeLens({x:Math.max(50,Math.min(950,state.lens.x+moves[e.key][0])),y:Math.max(100,Math.min(710,state.lens.y+moves[e.key][1]))});}};
function togglePause(){if(state.solved||state.flow==='discovery')return;state.paused=!state.paused;if(state.paused)audio.stop();refresh();}
document.addEventListener('keydown',e=>{if(e.defaultPrevented)return;if(e.key==='Escape'&&modalOpen){started?closeDialog():welcome();}if(e.code==='Space'&&!modalOpen&&!['BUTTON','INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();togglePause();}if(e.key==='Tab'&&modalOpen){const items=[...$('dialog').querySelectorAll('button:not([hidden]):not(:disabled),input:not(:disabled),select:not([hidden]):not(:disabled),summary,textarea,a')].filter(e=>e.getClientRects().length),first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('dialog'))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
document.addEventListener('visibilitychange',()=>{lastFrame=performance.now();if(document.hidden){audio.stop();persistInvestigation();}});
$('pause').onclick=togglePause;$('speed').onclick=()=>{state.speed=state.speed===1?2:state.speed===2?4:1;refresh();};$('lens').onclick=()=>{state.lens.active=!state.lens.active;tutorialEvent(state,'lens-enabled');if(state.tutorial.enabled&&state.tutorial.step==='place-lens')audio.speak('watch');refresh();};$('bell').onclick=()=>use('bell');$('sprinkler').onclick=()=>use('sprinkler');$('notebook').onclick=()=>notebook();$('aside-notebook').onclick=()=>notebook();$('accuse').onclick=accusation;$('hint').onclick=hint;$('context-help').onclick=help;$('settings').onclick=settings;$('cases').onclick=caseSelection;$('restart').onclick=()=>startCase(state.index,{tutorial:state.tutorial.enabled});$('guide-action').onclick=doNext;$('next-action').onclick=doNext;
$('skip-tutorial').onclick=skipTraining;$('open-finding').onclick=()=>{const id=state.lastFinding?.id,c=state.case.clues.find(c=>c.id===id);notebook(c?.kind==='testimony'?'people':id?.startsWith('pre-')||id?.startsWith('watch-')?'case':'evidence',id);};
$('cinema').onclick=()=>document.body.classList.add('cinema');$('exit-cinema').onclick=()=>document.body.classList.remove('cinema');$('map-buttons').innerHTML=[...RESIDENTS.map(r=>`<button data-resident="${r.id}">${r.name}</button>`),...LOCATIONS.map(l=>`<button data-location="${l.id}">${l.name}</button>`)].join('');document.querySelectorAll('[data-resident]').forEach(b=>b.onclick=()=>residentDialog(b.dataset.resident));document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>locationDialog(b.dataset.location));
window.addEventListener('pagehide',persistInvestigation);
document.addEventListener('click',()=>queueMicrotask(persistInvestigation));document.addEventListener('change',()=>queueMicrotask(persistInvestigation));
let uiTimer=0,lastWorldState=null,lastWorldWidth=0;
function frame(now){
 const elapsed=Math.min(1,Math.max(0,(now-lastFrame)/1000||0));lastFrame=now;const playing=started&&!modalOpen&&!picker.opened&&!document.hidden&&!state.paused&&!state.solved;
 for(const dt of playing?frameSteps(elapsed):[]){if(state.solved||modalOpen)break;if(state.reconstructing){if(state.reconTime>=19.8&&audio.busy)continue;const done=reconstructionStep(state,dt),segment=Math.min(2,Math.floor(state.reconTime/6));if(segment!==reconSegment){reconSegment=segment;if(segment===2)audio.speak('reconstruction',state.case.culprit);}if(done){state.reconstructing=false;state.solved=true;result();}}
 else{const oldFlow=state.flow,oldStep=state.tutorial.step,oldNight=state.nightElapsed;update(state,dt);audio.tick(dt);if(state.flow==='night'&&oldNight<3&&state.nightElapsed>=3)audio.incident(state.case.id);const signal=state.signals.find(x=>!x.spoken&&x.event);if(signal&&!state.tutorial.enabled&&!audio.busy){signal.spoken=true;audio.ambientEvent(signal.event,signal.resident);}if(oldFlow!==state.flow&&state.flow==='discovery'){audio.speak('discovery');audio.bell();refresh();}if(oldStep==='watch'&&state.tutorial.step==='notebook-before')refresh();if(state.flow==='investigate'&&!tutorialBlocking(state)){stuckTime+=dt;if(stuckTime>90&&!hintOffered){hintOffered=true;toast('רוצים כיוון? בעזרה מחכה רמז לבחירתכם.');}}}}
 if(playing&&!tutorialBlocking(state)&&state.flow==='observe'&&earlyLines.length){earlyElapsed+=elapsed;if(earlyElapsed>1.2&&!audio.busy){
 const line=earlyLines.shift(),r=RESIDENTS.find(r=>r.id===line.resident)||SUPPORTING.find(r=>r.id===line.resident);if(!state.selection)state.selection={type:RESIDENTS.includes(r)?'resident':'support',id:r.id};
 toast(r.name+' פוגש אתכם בתחילת המשמרת.');audio.ambientEvent('encounter',r.id);earlyElapsed=0;
 }}

 renderPortraits();
 // Dialogs pause the world. Keep its backdrop still instead of repainting the
 // full neighborhood under the blur every frame; the speaking portrait stays live.
 if(!modalOpen||lastWorldState!==state||lastWorldWidth!==canvas.clientWidth){render(canvas,state,elapsed,playing&&(!tutorialBlocking(state)||state.tutorial.step==='watch'));lastWorldState=state;lastWorldWidth=canvas.clientWidth;}
 coach.update();checkpointTimer+=elapsed;const signature=[state.serial,state.flow,state.tutorial.step,state.bell,state.sprinkler,state.hints,state.attempts].join(':');if(started&&(checkpointTimer>=1||signature!==lastCheckpointSignature)){checkpointTimer=0;lastCheckpointSignature=signature;persistInvestigation();}uiTimer+=elapsed;if(uiTimer>.2){uiTimer=0;refresh();}requestAnimationFrame(frame);
}
await artReady;refresh();welcome();const dubbingReturn=new URLSearchParams(location.search).get('dubbing');if(['activate','paid-return'].includes(dubbingReturn))dubbing.open(0,{activate:dubbingReturn==='activate',paidReturn:dubbingReturn==='paid-return'});requestAnimationFrame(frame);
